// <auto-generated />
using ForumService.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForumService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210812120101_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForumService.Entity.Forum", b =>
                {
                    b.Property<int>("ForumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ForumDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("LogoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ForumID");

                    b.ToTable("Forum");

                    b.HasData(
                        new
                        {
                            ForumID = 1,
                            ForumDescription = "This is forum about cars...",
                            ForumName = "Cars",
                            IsOpen = true,
                            LogoLink = "this is logo link",
                            UserID = 1
                        },
                        new
                        {
                            ForumID = 2,
                            ForumDescription = "This is forum about toys...",
                            ForumName = "Toys",
                            IsOpen = false,
                            LogoLink = "this is logo link",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("ForumService.Entity.ForumMessage", b =>
                {
                    b.Property<int>("ForumMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForumID")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ForumMessageID");

                    b.HasIndex("ForumID");

                    b.ToTable("ForumMessage");

                    b.HasData(
                        new
                        {
                            ForumMessageID = 1,
                            Body = "My car is better than yours...",
                            ForumID = 1,
                            SenderID = 1,
                            Title = "This is first message in forum...."
                        },
                        new
                        {
                            ForumMessageID = 2,
                            Body = "No, my car is better than yours... I have lamborghini",
                            ForumID = 1,
                            SenderID = 3,
                            Title = "This is second message in forum...."
                        },
                        new
                        {
                            ForumMessageID = 11,
                            Body = "My toy is better than yours...",
                            ForumID = 2,
                            SenderID = 1,
                            Title = "This is first message in forum...."
                        },
                        new
                        {
                            ForumMessageID = 12,
                            Body = "No, my toy is better than yours... I have barbie",
                            ForumID = 2,
                            SenderID = 3,
                            Title = "This is second message in forum...."
                        });
                });

            modelBuilder.Entity("ForumService.Entity.ForumMessage", b =>
                {
                    b.HasOne("ForumService.Entity.Forum", "Forum")
                        .WithMany()
                        .HasForeignKey("ForumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forum");
                });
#pragma warning restore 612, 618
        }
    }
}
